# Generated by Django 5.2 on 2025-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_forum',
            old_name='article_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blog_forum',
            name='text',
        ),
        migrations.AddField(
            model_name='blog_forum',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
