# Generated by Django 5.2.1 on 2025-05-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='priece',
            new_name='price',
        ),
    ]
